APEC/Areas/Admin/Controllers/BlockController.cs
using APEC.DOMAIN.Infrastructure;
using APEC.DOMAIN.Models;
using APEC.DOMAIN.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace APEC.Areas.Admin.Controllers
{
    [Authorize]
    public class BlockController : Controller
    {
        private IBlockRepository _blockRepository;
        private IDistrictRepository _districtRepository;
        private IUnitofWork unitOfWork;

        public BlockController(IBlockRepository blockRepository, IDistrictRepository districtRepository, IUnitofWork unitOfWork)
        {
            _blockRepository = blockRepository;
            _districtRepository = districtRepository;
            this.unitOfWork = unitOfWork;
        }

        // GET: Admin/Block
        public ActionResult Index(int? districtId)
        {
            var _list = _districtRepository.GetAll();
            ViewBag.DistrictId = new SelectList(_list, "DistrictId", "Name");
            IEnumerable<Block> blocks;
            if (districtId == null)
                districtId = _list.FirstOrDefault().DistrictId;

            blocks = _blockRepository.GetAll().Where(b => b.DistrictId == districtId);
            return View(blocks);
        }

        // GET: Admin/Block/Create
        public ActionResult Create()
        {
            var _list = _districtRepository.GetAll();
            ViewBag.DistrictId = new SelectList(_list, "DistrictId", "Name");
            return View();
        }

        // POST: Admin/Block/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                Block obj = new Block();
                TryUpdateModel(obj);
                _blockRepository.Add(obj);
                unitOfWork.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Block/Edit/5
        public ActionResult Edit(int id)
        {
            var _list = _districtRepository.GetAll();
            ViewBag.DistrictId = new SelectList(_list, "DistrictId", "Name");
            var block = _blockRepository.GetByID(id);

            return View(block);
        }

        // POST: Admin/Block/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                Block obj = new Block();
                TryUpdateModel(obj);
                _blockRepository.Update(obj);
                unitOfWork.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // POST: Admin/Block/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                var obj = _blockRepository.GetByID(id);
                _blockRepository.Delete(obj);
                unitOfWork.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

APEC/Areas/Admin/Controllers/ClientController.cs
using APEC.DOMAIN.Infrastructure;
using APEC.DOMAIN.Models;
using APEC.DOMAIN.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace APEC.Areas.Admin.Controllers
{
     [Authorize]
    public class ClientController : Controller
    {
        // GET: Admin/Client_
        private IClientRepository _iClientRepository;
        private IDistrictRepository _districtRepository;

        private IUnitofWork _unitOfWork;

        public ClientController(IClientRepository iClientRepository, IUnitofWork iUnitofWork ,IDistrictRepository districtRepository)
        {
            _iClientRepository = iClientRepository;
            _unitOfWork = iUnitofWork;
            _districtRepository = districtRepository;
        }
        public ActionResult Index()
        {
            var Client = _iClientRepository.GetAll();
            return View(Client);
        }

        // GET: Admin/Client/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/Client/Create
        public ActionResult Create()
        {
            var _list = _districtRepository.GetAll();
            ViewBag.DistrictId = new SelectList(_list, "DistrictId", "Name");
            return View();
        }

        // POST: Admin/Client/Create
        [HttpPost]
        public ActionResult Create(Client client )
        {
            try
            {
                // TODO: Add insert logic here
                _iClientRepository.Add(client);
                _unitOfWork.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Client/Edit/5
        public ActionResult Edit(int id)
        {
             var client=_iClientRepository.GetByID(id);
             var _list = _districtRepository.GetAll();
             ViewBag.DistrictId = new SelectList(_list, "DistrictId", "Name",client.DistrictId);
            return View(client);
        }

        // POST: Admin/Client/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                Client client= new Client();
                TryUpdateModel(client);
                
                _iClientRepository.Update(client);
                _unitOfWork.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Client/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {

                var obj = _iClientRepository.GetByID(id);
                _iClientRepository.Delete(obj);
                _unitOfWork.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // POST: Admin/Client/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                var obj = _iClientRepository.GetByID(id);
                _iClientRepository.Delete(obj);
                _unitOfWork.SaveChanges();
                return RedirectToAction("Index");
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

APEC/Areas/Admin/Controllers/DistrictController.cs
using APEC.DOMAIN.Infrastructure;
using APEC.DOMAIN.Models;
using APEC.DOMAIN.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace APEC.Areas.Admin.Controllers
{
     [Authorize]
    public class DistrictController : Controller
    {
        private IDistrictRepository _districtRepo;
        private IBlockRepository _blockRepository;
        private IUnitofWork UnitOfWork;

        public DistrictController(IDistrictRepository districtRepo, IBlockRepository blockRepository, IUnitofWork unitOfWork)
        {
            _districtRepo = districtRepo;
            _blockRepository = blockRepository;
            UnitOfWork = unitOfWork;
        }

        // GET: Admin/District
        public ActionResult Index()
        {
            var districts = _districtRepo.GetAll();
            return View(districts);
        }

        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/District/Create
        [HttpPost]
        public ActionResult Create(District district)
        {
            try
            {
                // TODO: Add insert logic here
                _districtRepo.Add(district);
                UnitOfWork.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/District/Edit/5
        public ActionResult Edit(int id)
        {
            var obj = _districtRepo.GetByID(id);
            return View(obj);
        }

        // POST: Admin/District/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                District district = new District();
                TryUpdateModel(district);
                _districtRepo.Update(district);
                UnitOfWork.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // POST: Admin/District/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                
                var obj = _districtRepo.GetByID(id);
                _districtRepo.Delete(obj);
                UnitOfWork.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

APEC/Views/Shared/_AdminLayout.cshtml
@using Microsoft.AspNet.Identity;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>APEC Admin Console</title>
    @Styles.Render("~/Content/Admincss")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("APEC Admin Console", "Index", "Home", new { area = "Admin" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Request.IsAuthenticated)
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true">Masters <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Clients", "Index", "Client", new { area = "Admin" }, null)</li>
                                <li>@Html.ActionLink("Districts", "Index", "District", new { area = "Admin" }, null)</li>
                                <li>@Html.ActionLink("Blocks", "Index", "Block", new { area = "Admin" }, null)</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Jobs", "Index", "Jobs", new { area = "Admin" }, null)</li>
                                <li class="divider"></li>
                                <li><a href="#">One more separated link</a></li>
                            </ul>
                        </li>
                        <li>
                            <ul></ul>
                        </li>

                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - APEC Admin Console</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
    <link href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" type="text/css" rel="stylesheet" />
</body>
</html>

APEC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Avani Paridhi Group of Companies</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="Avani Paridhi Group of Companies">
    <link rel="stylesheet" type="text/css" href="~/css/colors/red.css" title="red" media="screen" />

    <!--[if IE 8]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
    <!--[if lt IE 9]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div id="container" class="boxed-page">
        <div class="hidden-header"></div>
        <header class="clearfix">
            <div class="top-bar dark-bar">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8">
                            <ul class="contact-details">
                                <li>
                                    <a href="#"><i class="fa fa-map-marker"></i> 16/34, Fawn Break Avenue, Sarojini Naidu Marg, Lucknow.</a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-envelope-o"></i> info@avaniParidhi.com</a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-phone"></i> +91-9452667888</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-4">
                            <ul class="social-list">
                                <li>
                                    <a class="facebook itl-tooltip" data-placement="bottom" title="Facebook" href="#"><i class="fa fa-facebook"></i></a>
                                </li>
                                <li>
                                    <a class="twitter itl-tooltip" data-placement="bottom" title="Twitter" href="#"><i class="fa fa-twitter"></i></a>
                                </li>
                                <li>
                                    <a class="google itl-tooltip" data-placement="bottom" title="Google Plus" href="#"><i class="fa fa-google-plus"></i></a>
                                </li>
                                <li>
                                    <a class="linkdin itl-tooltip" data-placement="bottom" title="Linkedin" href="#"><i class="fa fa-linkedin"></i></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="navbar navbar-default navbar-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <i class="fa fa-bars"></i>
                        </button>
                        <a class="navbar-brand" href="index.html" style="display:inline-flex;">
                            <img alt="" src='@Url.Content("~/images/logo.jpg")' style="height:50px;">
                            <div style="padding-top: 9px;padding-left: 20px;">Avani Paridhi Energy and Communications (P) Ltd.</div>
                        </a>
                    </div>
                    <div class="navbar-collapse collapse" style="height: 79px !important;">
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                @Html.ActionLink("Home", "Index", "Home", null, new { @class = (ViewContext.RouteData.Values["controller"].ToString() == "Home" && ViewContext.RouteData.Values["action"].ToString() == "I ndex" ? "active" : "") })
                            </li>
                            <li>
                                @Html.ActionLink("Registration", "Index", "Registration", null, new { @class = (ViewContext.RouteData.Values["controller"].ToString() == "Registration" ? "active" : "") })
                            </li>
                            <li>
                                @Html.ActionLink("Vacancies", "Jobs", "Home", null, new { @class = (ViewContext.RouteData.Values["action"].ToString() == "Jobs" ? "active" : "") })
                            </li>
                            <li>
                                @Html.ActionLink("Downloads", "Index", "Downloads", null, new { @class = (ViewContext.RouteData.Values["controller"].ToString() == "Downloads" ? "active" : "") })
                            </li>
                            <li>
                                @Html.ActionLink("Clients", "Index", "Clients", null, new { @class = (ViewContext.RouteData.Values["controller"].ToString() == "Clients" ? "active" : "") })
                            </li>
                            <li>
                                @Html.ActionLink("News & Gallery", "Index", "NewsGallery", null, new { @class = (ViewContext.RouteData.Values["controller"].ToString() == "Home" && ViewContext.RouteData.Values["action"].ToString() == "News" ? "active" : "") })
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- Mobile Menu Start -->
                <ul class="wpb-mobile-menu">
                    <li>
                        <a class="active" href="index.html">Home</a>
                    </li>
                    <li>
                        <a href="about.html">Registration</a>
                    </li>
                    <li>
                        <a href="#">Vacancies</a>
                    </li>
                    <li>
                        <a href="portfolio-3.html">Downloads</a>
                    </li>
                    <li>
                        <a href="blog.html">Clients</a>
                    </li>
                    <li>
                        <a href="contact.html">News & Gallery</a>
                    </li>
                </ul>
                <!-- Mobile Menu End -->
            </div>
            <!-- End Header ( Logo & Naviagtion ) -->
        </header>
        <!-- Start HomePage Slider -->
        @RenderBody()
        <footer>
            <div class="container">
                <div class="row footer-widgets">
                    <div class="col-md-6">
                        <div class="footer-widget mail-subscribe-widget">
                            <b>M/S Avani Paridhi Energy & Communications (P) Ltd.</b> is a company registered as per Companies Registration act India. M/s APEC is also an ISO 9001 certified company.
                        </div>
                        <div class="footer-widget social-widget">
                            <h4>Follow Us<span class="head-line"></span></h4>
                            <ul class="social-icons">
                                <li>
                                    <a class="facebook" href="#"><i class="fa fa-facebook"></i></a>
                                </li>
                                <li>
                                    <a class="twitter" href="#"><i class="fa fa-twitter"></i></a>
                                </li>
                                <li>
                                    <a class="google" href="#"><i class="fa fa-google-plus"></i></a>
                                </li>
                                <li>
                                    <a class="linkdin" href="#"><i class="fa fa-linkedin"></i></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="footer-widget contact-widget">
                            <h4><img src="~/images/logo.jpg" class="img-responsive" alt="Footer Logo" style="height:50px;" /></h4>
                            <p>
                                <b>Head Office:</b>
                                B-124, Awas Vikas Colony
                                Banda-210001.<br />
                                <b>Branch Office:</b>
                                16/34, Fawn Break Avenue
                                Sarojini Naidu Marg
                                Near Honda Hospital
                                Lucknow-226001.
                            </p>
                            <ul>
                                <li><span>Phone Number:</span> +91-9452667888, Monday to Friday, 10:00 AM to 6:00 PM Only</li>
                                <li><span>Email:</span> info@avaniparidhi.com</li>
                                <li><span>Website:</span> www.avaniparidhi.com</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="copyright-section">
                    <div class="row">
                        <div class="col-md-6">
                            <p>&copy; 2016 APEC - All Rights Reserved <a href="http://avaniparidhi.com">APEC</a> </p>
                        </div>
                        <div class="col-md-6">
                            <ul class="footer-nav">
                                <li>@Html.ActionLink("Admin Console", "Index", "Home", new { area = "Admin" }, new { @class = (ViewContext.RouteData.Values["controller"].ToString() == "Vacancies" ? "active" : "") })</li>
                                <li><a href="#">Privacy Policy</a></li>
                                <li><a href="#">Contact</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    <a href="#" class="back-to-top"><i class="fa fa-angle-up"></i></a>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/extScripts")
    @RenderSection("scripts", required: false)
</body>
</html>